import React,{useEffect,useState} from "react";
export default function Admin(){
  const [products,setProducts]=useState([]); const [loading,setLoading]=useState(true);
  const [form,setForm]=useState({id:"",title:"",price:"",unit:"",category:"",image:"/images/placeholder.svg",description:""});
  const [editingId,setEditingId]=useState(null);
  useEffect(()=>{ fetch("/products.json").then(r=>r.json()).then(d=>{setProducts(Array.isArray(d)?d:[]);setLoading(false)}).catch(()=>{setProducts([]);setLoading(false)}) },[]);
  function reset(){ setEditingId(null); setForm({id:"",title:"",price:"",unit:"",category:"",image:"/images/placeholder.svg",description:""}); }
  function save(){ const next = editingId ? products.map(x=> x.id===editingId?({...form}):x) : ([{...form,id:form.id||('prod-'+Date.now())},...products]); setProducts(next); reset(); console.log("=== UPDATED PRODUCTS JSON ==="); console.log(JSON.stringify(next,null,2)); alert("Products updated in memory. JSON printed to console.") }
  function remove(id){ const next = products.filter(x=>x.id!==id); setProducts(next); console.log("=== UPDATED PRODUCTS JSON ==="); console.log(JSON.stringify(next,null,2)); alert("Deleted in memory. JSON printed to console.") }
  if(loading) return <div style={{padding:20}}>Loading...</div>;
  return <div style={{padding:20}}><h2>Admin</h2><div style={{display:'flex',gap:20}}><div style={{flex:1}}><h4>{editingId?"Edit":"New"}</h4><input placeholder="id" value={form.id} onChange={e=>setForm({...form,id:e.target.value})}/><input placeholder="title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="price" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input placeholder="unit" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}/><input placeholder="image" value={form.image} onChange={e=>setForm({...form,image:e.target.value})}/><textarea placeholder="desc" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div style={{marginTop:8}}><button onClick={save}>Save</button><button onClick={reset}>Reset</button></div></div><div style={{flex:2}}><h4>Products ({products.length})</h4><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(220px,1fr))',gap:12}}>{products.map(p=> <div key={p.id} style={{padding:10,background:'#fff',borderRadius:8}}><strong>{p.title}</strong><div>?{p.price} / {p.unit}</div><div style={{marginTop:6}}>{p.description?.slice(0,60)}</div><div style={{marginTop:8}}><button onClick={()=>{setEditingId(p.id); setForm({...p}); window.scrollTo(0,0)}}>Edit</button><button onClick={()=>remove(p.id)}>Delete</button></div></div>)}</div></div></div></div>
